create table clientes (
	cpf varchar (15) PRIMARY KEY ,
	nome varchar (100),
	logradouro varchar (100),
	cidade varchar (60),
	uf char(2),
	bairro varchar (40),
	cep CHAR (9),
	email varchar (60)
);

create table cliente_tel (
	id_tel int primary key ,
	cpf varchar (15) ,
	telefone varchar (15) ,
	
	constraint fk_cpf foreign key (cpf) references clientes (cpf)
);

create table pet (
	cod_animal int generated by default as identity ,
	cpf varchar (15) ,
	nome varchar (30) ,
	data_nascimento date ,
	raca varchar (15) ,
	tipo varchar (15) ,
	
	constraint pk_pet primary key (cod_animal) ,
	constraint fk_cpf foreign key (cpf) references clientes (cpf)
);

CREATE SEQUENCE pet_seq START WITH 1 INCREMENT BY 1;

create table empregados (
	id_empregado int primary key generated by default as identity ,
	cpf int ,
	nome varchar (100) ,
	logradouro varchar (100),
	cidade varchar (60),
	uf char(2),
	bairro varchar (40),
	cep CHAR (9),
	email varchar (60)
);

create table medicos (
	crmv int primary key ,
	id_empregado int ,
	
	constraint fk_id_empregado foreign key (id_empregado) references empregados (id_empregado)
);

create table medico_esp (
	crmv int primary key ,
	especialidade varchar(50) ,
	
	constraint fk_crmv foreign key (crmv) references medicos (crmv)
);

create table empregado_tel (
	id_empregado int primary key ,
	telefone int ,
	
	constraint fk_id foreign key (id_empregado) references empregados (id_empregado)
);

create table recepcionistas (
	cod_recepcionista int primary key generated by default as identity ,
	id_empregado int ,
	
	constraint fk_id_empregado foreign key (id_empregado) references empregados (id_empregado)
);

create table consultas (
	cod_consulta int primary key generated by default as identity ,
	crmv int , 
	cod_animal int ,
	cod_recepcionista int ,
	valor numeric(7,2) ,
	data_consulta date ,
	hora_consulta time ,
	
	constraint fk_crmv foreign key (crmv) references medicos (crmv) ,
	constraint fk_cod_animal foreign key (cod_animal) references pet (cod_animal)
);