ALTER TABLE consultas
    ADD CONSTRAINT fk_cod_recepcionista FOREIGN KEY (cod_recepcionista) REFERENCES recepcionistas (cod_recepcionista);
ALTER TABLE empregados ADD telefone varchar (15);

DROP TABLE empregado_tel;
DROP TABLE medico_esp;

create table medico_esp (
    id_esp int primary key generated by default as identity ,
	crmv int ,
	especialidade varchar(50) ,
	
	constraint fk_crmv foreign key (crmv) references medicos (crmv)
);
