CREATE SEQUENCE empregados_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE recepcionistas_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE cliente_tel_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE consultas_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE medico_esp_seq START WITH 1 INCREMENT BY 1;